# **Practice 8: Fundamental Subspaces with application to LTI Systems**
## **Goals for today**

---

During today practice we will:
*   Exploit a structure of linear mapping between inputs and outputs.


## **Four Fundamental Subspaces. Recall**
---
>As we have studied on the lectures there are four fundamental subspaces accompanying any linear operator (matrix) $\mathbf{A}^{m \times n}$, namely:
>*   **Column** space (range, image): $\mathcal{C}(\mathbf{A}) \in \mathbb{R}^m$ 
>*   **Null** space (kernel): $\mathcal{N}(\mathbf{A}) \in \mathbb{R}^n$
>*   **Row** space: $\mathcal{R}(\mathbf{A}) = \mathcal{C}(\mathbf{A}^T)  \in \mathbb{R}^n$
>*   **Left null** space: $\mathcal{N}(\mathbf{A}^T) \in \mathbb{R}^m$
---






### **SVD $\rightarrow$Four Fundamental Subspaces**
Outstanding is that SVD directly provides all **four fundamental subspaces** at once. 

---

\begin{equation}
\mathbf{A} = \mathbf{U}\mathbf{S}\mathbf{V}^T = \begin{bmatrix}\underset{m \times r}{\mathbf{U}_r} & \underset{m \times m - r}{\mathbf{U}_n}
\end{bmatrix}
\begin{bmatrix}
\underset{r \times r}{\mathbf{S}_r} & \underset{r \times n - r}{\mathbf{0}} \\ 
\underset{m - r \times r}{\mathbf{0}} & 
\underset{m - r \times n - r}{\mathbf{0}}
\end{bmatrix}
\begin{bmatrix}\underset{n \times r}{\mathbf{V}_r} & \underset{n \times n -r}{\mathbf{V}_n}
\end{bmatrix}^T
= \mathbf{U}_r \mathbf{S}_r \mathbf{V}^T_r
\end{equation}

---

*   **Column space** $\mathcal{C}(\mathbf{A})$is spanned by first $r$ vectors in $\mathbf{U}_r$
*  **Left null space** $\mathcal{N}(\mathbf{A}^T)$ is spanned by $m-r$ vectors in $\mathbf{U}_n$
*   **Row space** $\mathcal{R}(\mathbf{A}^T)$is spanned by first $r$ right singular vectors in $\mathbf{V}_r$
*  **Null space** $\mathcal{N}(\mathbf{A})$ is spanned by $n-r$ vectors in $\mathbf{V}_n$




---

In [ ]:
# from numpy import array
import numpy as np
from numpy.linalg import svd

A = [[0, 0], 
     [0, -1]]
A = np.array(A)

U, S, VT = svd(A, full_matrices=True)

# Let's print out the SVD matrices:
print(f"Left Singular Vectors:\n {U}\n")
print(f"Singular Values:\n {S}\n")
print(f"Right Singular Vectors:\n {VT.T}\n")


Left Singular Vectors:
 [[0. 1.]
 [1. 0.]]

Singular Values:
 [1. 0.]

Right Singular Vectors:
 [[-0.  1.]
 [-1.  0.]]

[1. 0.]
[0. 0.]


In [ ]:
# Fundamental subspaces are given by slicing resulting matrices

## **Applications to the LTI Systems**

### **Equilibrium Points of Uncontrolled System**

Given LTI system $\dot{\mathbf{x}} = \mathbf{A}\mathbf{x}$, where $\mathbf{x} \in \mathbb{R}^n$, $\mathbf{u} \in \mathbb{R}^m$, find all equalibrium states, namely:
\begin{equation}
\dot{\mathbf{x}} = \mathbf{A}\mathbf{x} = 0
\end{equation}

The all posible equalibrium points thus given by $\mathbf{x}_e = \mathbf{N}\mathbf{z}$, $\forall \mathbf{z}$


In [ ]:
from numpy import hstack
A = [[0, 1],
     [-2,-3]]
B = [[0], [1]]

M = hstack((A,B))

print(f'Stacked matrix:\n {M}')

U,S,VT = svd(M, full_matrices=True)
print(f'Left singular vectors:\n {U}')
print(f'Singular values:\n {S}')
print(f'Right singular vectors:\n {VT.T}')

Stacked matrix:
 [[ 0  1  0]
 [-2 -3  1]]
Left singular vectors:
 [[-0.21452344  0.97671884]
 [ 0.97671884  0.21452344]]
Singular values:
 [3.82869567 0.58402865]
Right singular vectors:
 [[-0.5102097  -0.73463328  0.4472136 ]
 [-0.82134498  0.57043179  0.        ]
 [ 0.25510485  0.36731664  0.89442719]]


### **Equilibrium Points and Feedforward**

Given LTI system $\dot{\mathbf{x}} = \mathbf{A} \mathbf{x} + \mathbf{B} \mathbf{u}$, where $\mathbf{x} \in \mathbb{R}^n$, $\mathbf{u} \in \mathbb{R}^m$, find all states that can be made into fixed points with a constant control law.


Let us find null space of the matrix $\begin{bmatrix} \mathbf{A} & \mathbf{B} \end{bmatrix}$ as $\mathbf{N} = \text{null} (\begin{bmatrix} \mathbf{A} & \mathbf{B} \end{bmatrix})$. 

We can find all $\mathbf{x}$, $\mathbf{u}$ pairs that produce equilibrium points as follows: $\begin{bmatrix} \mathbf{x} \\ \mathbf{u} \end{bmatrix} = \mathbf{N} \mathbf{z}$, $\forall \mathbf{z}$



In [ ]:
from numpy import hstack
A = [[0, 1],
     [-2,-3]]
B = [[0], [1]]

M = hstack((A,B))

print(f'Stacked matrix:\n {M}')

U,S,VT = svd(M, full_matrices=True)
print(f'Left singular vectors:\n {U}')
print(f'Singular values:\n {S}')
print(f'Right singular vectors:\n {VT.T}')

Stacked matrix:
 [[ 0  1  0]
 [-2 -3  1]]
Left singular vectors:
 [[-0.21452344  0.97671884]
 [ 0.97671884  0.21452344]]
Singular values:
 [3.82869567 0.58402865]
Right singular vectors:
 [[-0.5102097  -0.73463328  0.4472136 ]
 [-0.82134498  0.57043179  0.        ]
 [ 0.25510485  0.36731664  0.89442719]]


<!-- ### **Equilibrium Points and Feedforward** -->


Given LTI system $\dot{\mathbf{x}} = \mathbf{A} \mathbf{x} + \mathbf{B} \mathbf{u}$, where $\mathbf{x} \in \mathbb{R}^n$, $\mathbf{u} \in \mathbb{R}^m$, 

1.   check if $\mathbf{x}_d$ can be transformed into a equilibrium point
2.   find control constant $\mathbf{u}_d$ that does it, given control law $\mathbf{u} = \mathbf{K}\mathbf{x} + \mathbf{u}_d$.


 We can check that $(\mathbf{A}-\mathbf{B}\mathbf{K}) \mathbf{x}_d + \mathbf{B} \mathbf{u}_d = \mathbf{0}$ has a solution, in other words that $-(\mathbf{A}-\mathbf{B}\mathbf{K}) \mathbf{x}^* \in \mathcal{C}(\mathbf{B})$. Resulting condition is given via projection into the left null space of $\mathbf{B}$: 
 $(\mathbf{I} - \mathbf{B}\mathbf{B}^+)(\mathbf{A}-\mathbf{B}\mathbf{K})\mathbf{x}_d = \mathbf{0}$

This means finding such $\mathbf{u}_d$ that $(\mathbf{A}-\mathbf{B}\mathbf{K}) \mathbf{x}_d + \mathbf{B}\mathbf{u}_d= \mathbf{0}$. This is done via pseudo-inverse, which provides exact solution, as long as it exists: $\mathbf{u}_d= -\mathbf{B}^+(\mathbf{A}-\mathbf{B}\mathbf{K}) \mathbf{x}_d$.


In [ ]:
# ADD YOUR CODE HERE